package:
  name: py3-semgrep
  version: 1.15.0
  epoch: 0
  description: Lightweight static analysis for many languages.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - '@local ./packages'
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - py3-wheel@local
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/returntocorp/semgrep/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: bced1c0baee4f3795c9c825508bb16d25a64e1adf354d07dcd4c5c36159c1e92
  - runs: |
      cd cli
      python setup.py sdist bdist_wheel
      python3 setup.py install --skip-build --root="${{targets.destdir}}"
  - uses: strip